import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Trading Disclaimer — Keystone AI Studio",
  description:
    "Trading Bot Terms and Risk Disclaimer for Keystone AI Studio.",
};

export default function TradingDisclaimerPage() {
  return (
    <article className="max-w-4xl mx-auto px-6 md:px-8 py-20 md:py-32">
      <header className="mb-16">
        <h1 className="font-headline text-5xl md:text-6xl text-on-surface mb-4">
          Trading Bot Terms &amp; Risk Disclaimer
        </h1>
        <p className="text-secondary font-label text-sm uppercase tracking-wider">
          Last updated: February 2026
        </p>
      </header>

      <div className="prose-keystone">
        <h2>Educational Use Only &mdash; Not Financial Advice</h2>
        <p>
          All content provided by the Service &mdash; including but not limited
          to:
        </p>
        <ul>
          <li>AI-generated market analysis</li>
          <li>Chart annotations</li>
          <li>Liquidity levels, scenarios, or trade logic</li>
          <li>Commentary in Discord, Telegram, or any platform</li>
        </ul>
        <p>is for educational and informational purposes only.</p>
        <p>Nothing provided constitutes:</p>
        <ul>
          <li>Investment advice</li>
          <li>Trading advice</li>
          <li>Financial, legal, or tax advice</li>
          <li>
            A recommendation to buy or sell any security, futures contract, or
            instrument
          </li>
          <li>
            Trade execution, account management, entry/exit instructions, or
            buy/sell signals
          </li>
        </ul>
        <p>
          You should consult a licensed financial professional before making any
          trading decisions. The Service does not execute trades, manage
          accounts, or provide specific trading instructions.
        </p>

        <h2>No Fiduciary or Advisory Relationship</h2>
        <p>Your use of the Service does not create:</p>
        <ul>
          <li>A fiduciary relationship</li>
          <li>An advisor-client relationship</li>
          <li>A broker, dealer, or investment advisory relationship</li>
        </ul>
        <p>
          Keystone AI Studio does not act on your behalf and does not manage
          funds or accounts.
        </p>
        <p>
          Keystone AI Studio is not registered as an investment adviser with the
          U.S. Securities and Exchange Commission (SEC) or any state regulatory
          authority.
        </p>

        <h2>Trading Risk Acknowledgement</h2>
        <p>
          Trading financial markets involves substantial risk, including the
          risk of total loss.
        </p>
        <p>You acknowledge and agree that:</p>
        <ul>
          <li>Past performance does not guarantee future results</li>
          <li>
            AI-generated analysis may be inaccurate, delayed, incomplete, or
            incorrect
          </li>
          <li>
            Market conditions can change rapidly and invalidate analysis
          </li>
          <li>
            You are solely responsible for all trading decisions and outcomes
          </li>
        </ul>

        <h2>No Guarantees or Promises</h2>
        <p>Keystone AI Studio makes no guarantees regarding:</p>
        <ul>
          <li>Accuracy</li>
          <li>Profitability</li>
          <li>Win rates</li>
          <li>Risk-reward outcomes</li>
          <li>Service availability</li>
        </ul>
        <p>
          Any examples, scenarios, or annotations shown are illustrative only.
        </p>

        <h2>AI &amp; System Limitations</h2>
        <p>You understand that:</p>
        <ul>
          <li>Responses may be generated by AI systems</li>
          <li>The bot may experience downtime, latency, or errors</li>
          <li>
            The Service may be unavailable due to maintenance, system sleep,
            connectivity issues, or platform limitations
          </li>
          <li>
            Keystone AI Studio is not liable for missed messages, delayed
            responses, or incomplete outputs
          </li>
        </ul>

        <h2>Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Keystone AI Studio shall not
          be liable for:
        </p>
        <ul>
          <li>Trading losses or missed opportunities</li>
          <li>Account drawdowns or liquidation</li>
          <li>Indirect, incidental, or consequential damages</li>
          <li>Reliance on AI-generated content</li>
        </ul>
        <p>Use of the Service is entirely at your own risk.</p>

        <h2>User Responsibility</h2>
        <p>You agree that:</p>
        <ul>
          <li>You are responsible for verifying all information</li>
          <li>You make independent trading decisions</li>
          <li>
            You comply with all applicable laws and regulations in your
            jurisdiction
          </li>
        </ul>

        <h2>Intellectual Property</h2>
        <p>
          All content, prompts, annotations, analysis frameworks, and outputs
          provided by the Service remain the intellectual property of Keystone
          AI Studio unless otherwise stated.
        </p>
        <p>Unauthorized redistribution or resale is prohibited.</p>

        <h2>Service Changes &amp; Termination</h2>
        <p>Keystone AI Studio reserves the right to:</p>
        <ul>
          <li>Modify, suspend, or terminate the Service at any time</li>
          <li>Change features, availability, or pricing without notice</li>
        </ul>

        <h2>Governing Law</h2>
        <p>
          These terms shall be governed by and construed in accordance with the
          laws of the State of Virginia, United States.
        </p>

        <h2>Payment &amp; Subscription Terms</h2>
        <p>
          All fees paid for access to the Service are final and non-refundable
          unless otherwise required by law.
        </p>
        <p>
          No refunds will be issued based on trading performance,
          dissatisfaction with analysis, or market outcomes.
        </p>
        <p>
          Keystone AI Studio reserves the right to suspend or terminate access
          to the Service at its sole discretion, including for violation of
          these terms.
        </p>

        <h2>Acceptance</h2>
        <p>
          By remaining in the Discord server, accessing the bot, or using the
          Service, you confirm that you understand and accept these terms in
          full.
        </p>
      </div>
    </article>
  );
}
